site_name: APEX Hands-On Workshop
site_description: Hands-On Workshop to build a first APEX Application with a lot of components
site_url: https://raiwil.github.io/apex_workshop/
repo_url: https://github.com/raiwil/apex_workshop
repo_name: raiwil/apex_workshop

theme:
  name: material
  language: de
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: deep orange
      accent: orange
  #    toggle:
  #      icon: material/weather-night
  #      name: Dark mode
  #  - scheme: slate
  #    primary: deep orange
  #    accent: orange
  #    toggle:
  #      icon: material/weather-sunny
  #      name: Light mode

nav:
  - Start: index.md
  - Workshop Notes: workshop-notes.md
  - Chapters:
      - '1. Getting started': 01-getting-started.md
      - '2. Application Customization': 02-application-customization.md
      - '3. Authentication' : 03-authentication.md
      - '4. Authorization': 04-authorization.md
      - '5. Maps': 05-maps.md
      - '6. RESTful Services': 06-restful-services.md
      - '7. Reporting & Search': 07-reporting-and-search.md
      - '8. Charts': 08-charts.md
      - '9. Files & Images': 09-files-images.md
      - '10. Calendars': 10-calendars.md
      - '11. JavaScript': 11-javascript.md
      - '12. Layout': 12-layout.md
      - '13. Data Loading': 13-data-loading.md
      - '14. Approvals & Workflows': 14-approvals-workflows.md
      - '15. Translations': 15-translations.md  
      - '16. Mobile Applications': 16-mobile-applications.md   
      - '17. AI in APEX': 17-ai-in-apex.md
      - '18. Application Lifecycle Management': 18-application-lifecycle-management.md
      - '19. Administration': 19-administration.md
      - '20. Forms - Updates over Joins': 20-forms.md
      - '21. Miscellaneous': 21-miscellaneous.md
      - '22. Links & Learning Resources': 22-links-learning-resources.md

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css
